### ISSUE TITLE
"no module named gi" in converting process

### ISSUE THREAD

**Issue by lnxpy** [pycdr/WM#2]
You may need to add vext and vext.gi modules in your dependencies in order to make `gi` module available on your imports.
Check this out:
https://askubuntu.com/questions/80448/what-would-cause-the-gi-module-to-be-missing-from-python

It obviously backs to the Linux-based distribution that user is running WM on. Hope it helps. :heart:

**Comment by pycdr** [comment]
Hi @lnxpy !
it seems that is the `playsound` library problem, however, [`playsound` developer](https://github.com/TaylorSMarks) is off for a long time! so, I will add an installer instead of `requirements.txt`.
i saw an issue on the library that may be helpful for now: [link](https://github.com/TaylorSMarks/playsound/issues/24).
it is added to `TODO.md` file and we will update it soon.
thanks.

**Comment by pycdr** [comment]
dear @lnxpy ,
thank to you, it is fixed now! the `playsound` is now removed and `play` command is replaced.
_now you can watch with sound! :)_
if you want to use it, please read the `README.md` again, there are somethings new.
